node:
  name: node1
  storage: "/data/files"

etcd:
  etcdEndpoints: "http://127.0.0.1:2379"
  address: "127.0.0.1:9000"
  ttl: 10
  dialTimeout: 5

log:
  Enable: "false"
  level: "info"
  encoding: "json"
  outputPaths:
    - "stdout"
    - "app.log"
  errorOutputPaths:
    - "stderr"
    - "app_err.log"
