# MinIO存储配置示例
# 适用于本地开发和测试环境

node:
  name: node1
  storage: "/data/files"

# 存储配置 - MinIO模式
storage:
  type: "s3"
  localRoot: "./storage"
  dataRoot: "./data"
  s3:
    bucket: "zfs-test"
    region: "us-east-1"
    prefix: "zfs/"
    # MinIO默认凭证
    accessKeyId: "minioadmin"
    secretAccessKey: "minioadmin"
    # MinIO endpoint
    endpoint: "http://localhost:9000"
    # MinIO需要路径风格访问
    forcePathStyle: true

etcd:
  etcdEndpoints: "http://127.0.0.1:2379"
  address: "127.0.0.1:9000"
  ttl: 10
  dialTimeout: 5

log:
  Enable: "false"
  level: "info"
  encoding: "json"
  outputPaths:
    - "stdout"
    - "app.log"
  errorOutputPaths:
    - "stderr"
    - "app_err.log"
